### ISSUE TITLE
IOS version

### ISSUE THREAD

**Issue by GokulDharumar** [mitchhymel/local_notifications#1]
Hi Mitch,

    Thank you so much for the plugin. Do you have an estimate for the ios version?

**Comment by mitchhymel** [comment]
I have zero ios experience, so I'm not sure how long it would take to add ios support. If I have free time this weekend, I'll take a look and maybe afterwards will be able to provide a better estimate.

**Comment by GokulDharumar** [comment]
Thanks mitch. It will be of great help for us ... we are deciding between
react native and flutter... and some of the features we have on flutter so
far supports only android version which will be a deal breaker for us.
Thanks again for the help.

**Comment by mitchhymel** [comment]
@GokulDharumar 
I added ios support with commit b9c7ad4f281a3c14cb018179d0d9f916662b7bca and also published the package to Pub at https://pub.dartlang.org/packages/local_notifications . Try it out and let me know if it works for your scenario.

**Comment by mitchhymel** [comment]
Going to close this, as basic ios support was added with b9c7ad4

**Comment by GokulDharumar** [comment]
Thanks so much for the fast response. Will take a look at it.

**Comment by GokulDharumar** [comment]
Hi Mitch,

  Started working on the ios plugin but it is failing with the below error

 === BUILD TARGET local_notifications OF PROJECT Pods WITH CONFIGURATION
Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/local_notifications-umbrella.h"
            ^
    ../work/push_notification/ios/Pods/Target Support
Files/local_notifications/local_notifications-umbrella.h:13:9: error:
include of non-modular header inside framework module
'local_notifications':
'/Users/gdharumar/.pub-cache/git/local_notifications-531e3ede54f58eb9a1bef2fb4d7a8d612d98ab1e/ios/Classes/LocalNotificationsPlugin.h'
    #import "LocalNotificationsPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module
'local_notifications'



Thanks
Gokul Dharumar
