### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by xiyionxiong** [mitchhymel/local_notifications#21]
`Launching lib/main.dart on iPhone XS in debug mode...
Starting Xcode build...
Xcode build done.                                            1.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET local_notifications OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/apanda/.pub-cache/hosted/pub.flutter-io.cn/local_notifications-0.0.7/ios/Classes/SwiftLocalNotificationsPlugin.swift:123:52: error: cannot call value of non-function type 'UNNotificationSound'
            content.sound = UNNotificationSound.default()
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
`
how can i solve it .

**Comment by subaharan** [comment]
Have you solved this issue?  I am facing the same.

**Comment by mitchhymel** [comment]
I highly recommend trying out [flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications). I'm not really working on this plugin anymore whereas flutter_local_notifications is relatively more active.
