### ISSUE TITLE
IOS build is failing

### ISSUE THREAD

**Issue by GokulDharumar** [mitchhymel/local_notifications#5]
Hi, I tried to use the plugin for IOS. Its working fine in android app. In ios i get the below error. Do i need any set up for ios project to work.

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET local_notifications OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/local_notifications-umbrella.h"
            ^
   /work/push_notification/ios/Pods/Target Support Files/local_notifications/local_notifications-umbrella.h:13:9: error: include of non-modular header inside framework module 'local_notifications': '.pub-cache/git/local_notifications-531e3ede54f58eb9a1bef2fb4d7a8d612d98ab1e/ios/Classes/LocalNotificationsPlugin.h'
    #import "LocalNotificationsPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'local_notifications'
Could not build the precompiled application for the device.

**Comment by mitchhymel** [comment]
I don't remember doing any special set up for the example project I used to test iOS support, but it's possible I missed some step to prepare the iOS part of the plugin for use via pub. Will try to look into this over the weekend.

**Comment by GokulDharumar** [comment]
Thanks mitch. We are currently looking at flutter and react native to start
our project. Some of the features react-native has is not in flutter which
is affecting us from using flutter.If you can help us out it will be really
great.

Thanks
Gokul Dharumar

**Comment by s-bauer** [comment]
Instead you can also copy the "example/ios/Podfile" from this repository to your "ios/Podfile" directory and add a .swift file to your Runner project, so it compiles correctly

**Comment by s-bauer** [comment]
@GokulDharumar There you go: https://github.com/s-bauer/loca_notifications_own/blob/master/example/ios/Podfile

Then add a .swift file to the Runner project like so https://imgur.com/a/3v3kH

Let me know if it works. I've been able to solve this problem in my own project, so we'll manage to fix it in yours too :)

**Comment by s-bauer** [comment]
@GokulDharumar  @mitchhymel I think this is a bug in flutter. I opened an issue. Let's see what the flutter devs have to say about this: https://github.com/flutter/flutter/issues/16097

**Comment by GokulDharumar** [comment]
@s-bauer thanks so much ... will wait for the update then :)

**Comment by s-bauer** [comment]
@mitchhymel It's a flutter related issue, so this issue can be closed. Maybe add a link to the issue in README.md and/or recommend them to use `flutter create -i swift` as a workaround.

**Comment by GokulDharumar** [comment]
@s-bauer thanks so much for your help... I copied your podfile and it started working. Hopefully flutter guys will fix it asap.

**Comment by mitchhymel** [comment]
Added a short statement to the readme pointing to this issue until the flutter issue is resolved with commit d7faf0c83286344d28c2958529280236930507b2 . Going to mark this issue as closed.
